include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_element: warning
    dead_code: warning

linter:
  rules:
    # Style
    - require_trailing_commas
    - sort_child_properties_last
    - always_declare_return_types

    # Performance
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_key_in_widget_constructors

    # Code cleanup
    - avoid_print
    - unnecessary_this
    - unnecessary_string_interpolations
    - unnecessary_brace_in_string_interps
    - unnecessary_nullable_for_final_variable_declarations

    # Safer async
    - avoid_void_async

    # Better Flutter practices
    - use_build_context_synchronously
    - no_logic_in_create_state
    - avoid_init_to_null
    - prefer_final_fields
    - prefer_final_locals
    - prefer_final_in_for_each

    # Readability
    - null_check_on_nullable_type_parameter
    - unnecessary_null_checks
    - prefer_if_null_operators
